name: Record animation

on: [push]

jobs:
  record:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Add competitors
        run: |
          git clone https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/lukicdarkoo/webots-competition-participant-template controllers/participant_controller
          cd controllers/contest_manager && make
      - name: Record and deploy the animation
        uses: cyberbotics/webots-animation-action@feature-competition
